[package]
name = "stock_portfolio"
version = "0.1.1"
authors = ["jrtabash"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
curl = "0.4.34"
clap = "2.33.3"
