[package]
name = "stock_portfolio"
version = "0.2.0"
authors = ["jrtabash"]
edition = "2018"

[[bin]]
name = "sp_report"
path = "src/main.rs"

[dependencies]
chrono = "0.4"
curl = "0.4.34"
clap = "2.33.3"
